version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6.10.2

    working_directory: ~/Sherwin-Dapito-Resume-Angular-5

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, we are now doing CI tests.

      - run:
          name: Print the Current Time
          command: date

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      # build
      - run:
          name: build angular app
          command: 'npm run-script build'

  # deploy_heroku
  deploy_heroku:
    docker:
      - image: circleci/node:6.10.2
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  
  # deploy_amazon
  deploy_amazon:
    docker:
      - image: circleci/node:6.10.2
    working_directory: ~/Sherwin-Dapito-Resume-Angular-5

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "87:cc:bc:35:b1:ed:e0:5e:6a:ed:94:03:db:6b:7d:50"
      -run: 
        name: Execute Deploy run-script
        command: |
          ssh -o StrictHostKeyChecking=no ubuntu@$AMAZON_HOST 'bash -c "sh automate.sh"'

workflows:
  version: 2
  build_and_deploy_amazon:
    jobs:
      - build
      - deploy_heroku:
          requires:
            - build
      - deploy_amazon:
          requires:
            - build
#          filters:
#            branches:
#              only: master